import {
  Activity,
  AppWindow,
  AudioLines,
  Bell,
  Bot,
  Boxes,
  CheckSquare2,
  ChevronDown,
  CircleCheckBig,
  Clock3,
  CreditCard,
  Copy,
  Database,
  FileChartColumn,
  FolderKanban,
  Gauge,
  GitBranch,
  LayoutDashboard,
  ListChecks,
  LockKeyhole,
  LogOut,
  Mail,
  Menu,
  MessageSquareText,
  Mic,
  Moon,
  Newspaper,
  PlugZap,
  Search,
  Settings,
  Send,
  Sparkles,
  Sun,
  TerminalSquare,
  Trash2,
  Plus,
  Play,
  RefreshCw,
  ArrowRight,
  Eye,
  WandSparkles,
  X,
  type LucideIcon,
} from "lucide-react";

import type { IconName } from "@/lib/modules";

const iconRegistry: Record<IconName, LucideIcon> = {
  dashboard: LayoutDashboard,
  mail: Mail,
  clock: Clock3,
  plans: ListChecks,
  browser: AppWindow,
  agents: Bot,
  activity: Activity,
  tokens: Gauge,
  api: PlugZap,
  github: GitBranch,
  chat: MessageSquareText,
  vault: Database,
  notifications: Bell,
  search: Search,
  settings: Settings,
  onboarding: Sparkles,
  status: CircleCheckBig,
  billing: CreditCard,
  digests: Newspaper,
  environments: Boxes,
  voice: AudioLines,
  todo: CheckSquare2,
  skills: WandSparkles,
  terminal: TerminalSquare,
  reports: FileChartColumn,
  folder: FolderKanban,
  menu: Menu,
  close: X,
  chevron: ChevronDown,
  sun: Sun,
  moon: Moon,
  microphone: Mic,
  lock: LockKeyhole,
  eye: Eye,
  arrow: ArrowRight,
  logout: LogOut,
  check: CircleCheckBig,
  trash: Trash2,
  plus: Plus,
  send: Send,
  refresh: RefreshCw,
  copy: Copy,
  play: Play,
};

export function Icon({ name, size = 18, strokeWidth = 1.8 }: { name: IconName; size?: number; strokeWidth?: number }) {
  const Glyph = iconRegistry[name];
  return <Glyph aria-hidden="true" size={size} strokeWidth={strokeWidth} />;
}
